version: '3.4'

services:
  multiapp:
    image: multiapp
    build:
      context: .
      dockerfile: multiapp/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database

  database:
    image: sqlserver
    build:
      context: ./multiapp/Dockerdb  # This path should match the folder structure exactly
      dockerfile: Dockerfile
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Sneha@1819"
      MSSQL_PID: "Express"