# Use the official Microsoft SQL Server image from Docker Hub
FROM mcr.microsoft.com/mssql/server:2019-latest

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=Sneha@1819
ENV MSSQL_PID=Express

# Expose port 1433
EXPOSE 1433
