name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step to login to Azure Container Registry
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: multiappregis.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push the first image (app)
      - name: Build and push the first image (app)
        uses: docker/build-push-action@v2
        with:
          context: ./multiapp # Context is the root directory containing the first Dockerfile
          file: ./multiapp/Dockerfile # Path to the first Dockerfile
          push: true
          tags: multiappregis.azurecr.io/app:latest # Replace with your app image tag

      # Build and push the second image (db)
      - name: Build and push the second image (db)
        uses: docker/build-push-action@v2
        with:
          context: ./multiapp # Ensure context includes both the csproj and Dockerfile paths
          file: ./multiapp/Dockerdb/Dockerfile # Path to the second Dockerfile
          push: true
          tags: multiappregis.azurecr.io/db:latest # Replace with your db image tag
