name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step to login to Azure Container Registry
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          login-server: multiappregis.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push the first image (app)
      - name: Build and push the first image (app)
        uses: docker/build-push-action@v2
        with:
          context: ./multiapp # Ensure this is the correct directory
          file: ./multiapp/Dockerfile # Path to the Dockerfile for the app
          push: true
          tags: multiappregis.azurecr.io/app:latest

      # Build and push the second image (db)
      - name: Build and push the second image (db)
        uses: docker/build-push-action@v2
        with:
          context: ./multiapp # Ensure context includes Dockerfile paths
          file: ./multiapp/Dockerdb/Dockerfile # Path to the Dockerfile for the db
          push: true
          tags: multiappregis.azurecr.io/db:latest
