name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step to checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Build and push the first image (app)
      - name: Build and push the first image (app)
        uses: docker/build-push-action@v2
        with:
          context: . # The context is the root of the repo; adjust if needed
          file: ./multiapp/Dockerfile # Path to the first Dockerfile
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/app:latest # Replace with your app image tag

      # Build and push the second image (db)
      - name: Build and push the second image (db)
        uses: docker/build-push-action@v2
        with:
          context: . # The context is the root of the repo; adjust if needed
          file: ./multiapp/Dockerdb/Dockerfile # Path to the second Dockerfile
          push: true
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/db:latest # Replace with your db image tag
