name: Build and Push Docker Images

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure Container Registry
      run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_NAME }}.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push Web image
      uses: docker/build-push-action@v2
      with:
        context: ./multiapp # Set the build context to the folder where the web Dockerfile is located
        file: ./multiapp/Dockerfile # Path to your web Dockerfile
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/web:latest

    - name: Build and push Db image
      uses: docker/build-push-action@v2
      with:
        context: ./multiapp/Dockerdb # Set the build context to the folder containing your Dockerdb directory
        file: ./multiapp/Dockerdb/Dockerfile # Correct path to the Dockerfile for the DB image
        push: true
        tags: ${{ secrets.ACR_NAME }}.azurecr.io/db:latest
